# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('client', models.CharField(choices=[('Client-A', 'Client-A'), ('Client-B', 'Client-B'), ('Client-C', 'Client-C'), ('Client-D', 'Client-D')], max_length=10)),
                ('client_priority', models.IntegerField()),
                ('target_date', models.DateField()),
                ('product_area', models.CharField(choices=[('None', 'None'), ('Policies', 'Policies'), ('Billing', 'Billing'), ('Claims', 'Claims'), ('Reports', 'Reports')], max_length=10)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
