# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('client_priority', models.IntegerField()),
                ('target_date', models.DateField()),
                ('product_area', models.CharField(choices=[('None', 'None'), ('Policies', 'Policies'), ('Billing', 'Billing'), ('Claims', 'Claims'), ('Reports', 'Reports')], default='None', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xceedance.Client')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set([('client', 'client_priority')]),
        ),
    ]
