# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xceedance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='client',
            field=models.CharField(choices=[('Client-A', 'Client-A'), ('Client-B', 'Client-B'), ('Client-C', 'Client-C'), ('Client-D', 'Client-D')], max_length=10),
        ),
        migrations.AlterField(
            model_name='feature',
            name='product_area',
            field=models.CharField(choices=[('None', 'None'), ('Policies', 'Policies'), ('Billing', 'Billing'), ('Claims', 'Claims'), ('Reports', 'Reports')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
