# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xceedance', '0003_feature_reporter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set([]),
        ),
    ]
